### ISSUE TITLE
How do I add records to a collection ? collection.addRows is not available 

### ISSUE THREAD

**Issue by djibomar** [Devorein/Nishan#22]
**Describe the bug**
Hello @Devorein  from the documentation, it seems that we can call **collection.addRows** however that method no longer exists.

How can I add records?

Also, how does the update work?

Thank you

**Comment by djibomar** [comment]
I got it to work.

`collection.createPages` is the correct method.

And if you need to update a record, I believe you can simply update the page.

**Comment by Devorein** [comment]
@djibomar Extremely sorry for that. The doc is still a bit outdated. Yes `collection.createPages` is the correct method. You can update in two ways
1. Using `collection.updatePages`
2. Using page instance's update method
