### ISSUE TITLE
Ability to searching a collection

### ISSUE THREAD

**Issue by djibomar** [Devorein/Nishan#23]
Hey @Devorein,

I was wondering if we could have the ability to search a collection?

I think in notion the endpoint being used is `queryCollection`.

Thanks

**Comment by Devorein** [comment]
Hey, @djibomar can you please explain a bit more about your question?
If you wanna get pages from a collection you can use the method `collection.getPages` based on any filters

**Comment by Devorein** [comment]
I'm closing the issue, for now. If you see that the above solution doesn't work, please reopen it.

**Comment by djibomar** [comment]
Hey I think **getPages** work. 

BTW Really Nice work here. 👏👏👏

**Comment by Devorein** [comment]
Appreciate the praise bud. I'm glad that that worked.
