### ISSUE TITLE
Question: Is it possible to list rows in a database?

### ISSUE THREAD

**Issue by jeffandersen** [Devorein/Nishan#31]
I'm trying to understand the hierarchy of the Nishan client, and I'm not 100% sure how to query the data I'm after.
My page structure is such:

- Top level page
  - Nested database
    - Row A
    - Row B
    - Row C
  - Other nested page

I want to be able to retrieve Row A, Row B, Row C as entries, but after reviewing the code I'm not sure this is exposed?

Thanks in advance

**Comment by Devorein** [comment]
@jeffandersen Is the nested database a child of the top level page? If so you can get the root level page first using the Space method `getTRootPages.` After that you could call the `getBlock` method of the nested page and get you nested databased based on any of its properties.

**Comment by Devorein** [comment]
Here is a little snippet of what could be the answer

## First method

```js
const {collection_view_page} = await space.getTRootPages((root_page)=>root_page.id === <page_id> /*You can use any other criteria*/);
const cvp = collection_view_page.get("page_id");
if(cvp){
	const collection = await cvp.getCollection();
	const rows = await collection.getPages((page)=>/*All the rows of the database is passed as a parameter to this callback*/)
}
```

## Second method

```js
const collections = await space.getRootCollections((collection )=>collection .id === <collection_id> /*You can use any other criteria*/);
const collection = collection.get("collection_id");
if(collection){
	const rows = await collection.getPages((page)=>/*All the rows of the database is passed as a parameter to this callback*/)
}
```

Hope this helps

**Comment by Devorein** [comment]
I hope the above solution worked. I'm closing the issue for now. If you face any further problems please reopen the issue.
