### ISSUE TITLE
Having some issues creating pages

### ISSUE THREAD

**Issue by Supesu** [Devorein/Nishan#78]
Hey @Devorein, I've been trying to create a collection view page and i've been having some trouble. it goes through without any errors, but when I check notion no page has been created... I've included the logs & code.

![image](https://user-images.githubusercontent.com/59186190/107317578-c89eff00-6aff-11eb-80ad-7b8078a0467b.png)
![image](https://user-images.githubusercontent.com/59186190/107317663-f126f900-6aff-11eb-98b2-84aff0322e29.png)
![image](https://user-images.githubusercontent.com/59186190/107317607-d5235780-6aff-11eb-85cf-cbd6a9e036d4.png) 

Am I doing something wrong here? My apologies if I am missing something obvious.

EDIT:  I thought I might add in yes, I have tried restarting notion and checking it on another device

**Comment by Devorein** [comment]
Hey seems like youre missing just a single thing. Please call `space.executeOperations` at the e d to persist it in notions db. Sorry for that trouble. If you face any other problems, feel free to ask.

**Comment by Supesu** [comment]
Thanks for the speedy reply,

all working fine now :)

**Comment by Devorein** [comment]
Awesome. Glad to hear that.
